CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	username VARCHAR(30) NOT NULL UNIQUE,
	bio VARCHAR(400),
	avatar VARCHAR(200),
	phone VARCHAR(25) UNIQUE,
	email VARCHAR(40) UNIQUE,
	password VARCHAR(50) NOT NULL,
	status VARCHAR(15) NOT NULL,
	CHECK(COALESCE(phone, email) IS NOT NULL)
);
